### PR TITLE
Default country code

### PR DESCRIPTION
**Pull request by dlondero**
Refs #12

### CODE REVIEW

**Comment by dlondero** [comment]
@alekitto you had in mind something like this?

**Comment by massimilianobraglia** [comment]
Hey @dlondero, thank you again!

I'm not sure about the name of that property: `Default country code` is something really bound to `libphonenumber` and not something related to our SDK (it is not used by our code apart from that). What do you think about it?

**Comment by alekitto** [comment]
Good point. Default country code could be misinterpreted as default value for `countryIso`.

Name should be changed to something that represents “phone country code default”

**Comment by dlondero** [comment]
How about `$defaultPhoneCountryCode`?

**Comment by massimilianobraglia** [comment]
SGTM. @alekitto?

**Comment by alekitto** [comment]
Yes, good enough 👍

**Comment by alekitto** [comment]
Thanks @dlondero!

**Pull request merged**
